language: android
android:
  components:
    - tools
    - build-tools-29.0.2
    - android-29
    - platform-tools
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'

sudo: required
jdk:
  - oraclejdk8
install:
  - true

script:
  - ./gradlew lint --console verbose -w -e