name: Android CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: KtLint
        run: bash ./gradlew ktlintCheck
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Coverage
        run: ./gradlew jacocoTestReport
      - name: Upload Coverage
        run: bash <(curl -s https://codecov.io/bash)
      - name: Upload testDebugUnitTest Results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: testDebugUnitTest
          path: library/build/reports/tests/testDebugUnitTest
      - name: Upload testDebugUnitTest Results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: testReleaseUnitTest
          path: library/build/reports/tests/testReleaseUnitTest

